[package]
name = "ntt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bls12_381 = "0.8.0"
bls12_381 = {path = "lib/bls12_381"}
ff = "0.13.0"